version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Compile the source
          command: npm run compile
      - run:
          name: Run ESLint checks
          command: npm run lint
      - run:
          name: Run Prettier checks
          command: npm run format-check
  test:
    docker:
      - image: cimg/openjdk:20.0.2-node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Compile the source
          command: npm run compile
      - run:
          name: Run tests
          command: npm run test

  publish:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Compile the source
          command: rm -rf dist && npm run compile
      - run:
          name: Publish to NPM
          command: npm publish
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Configure NPM
                command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

workflows:
  build_test_deploy:
    jobs:
      - lint:
          name: Run linter and formatter
          filters:
            tags:
              only: /.*/

      - test:
          name: Run tests
          filters:
            tags:
              only: /.*/

      - publish:
          name: Publish to NPM
          requires: [lint, test]
          filters:
            branches:
              only:
                - main
            tags:
              only: /^v\d+\.\d+\.\d+$/
