version: 2.1

commands:
  install_deps:
    description: "Install project dependencies"
    steps:
      - run: npm install

jobs:
  lint_and_format_check:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: npm run lint
      - run: npm run format-check
  compile:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: rm -rf lib
      - run: npm run build
  test:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: cd __tests__ && echo "$FB_SERVICE_ACCOUNT_KEY" | base64 --decode > service-account.json
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - lint_and_format_check
      - compile
      - test:
          requires:
            - compile
            - lint_and_format_check
