name: Publish package

on:
  workflow_dispatch:
    inputs:
      version_increment:
        type: choice
        required: true
        description: 'Select version increment type'
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'version'
  cancel-in-progress: true

jobs:
  bump_version_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Set git identity
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Configure NPM
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Bump version
        run: npm version ${{ inputs.version_increment }}

      - name: Push commit and create tag and release
        run: |
          version="$(jq -r .version package.json)"
          git push origin
          git push origin "v$version"
          gh release create "v$version" --title "v$version"

      - name: Publish the package to NPM
        run: npm publish
